c('Article',
'Author Correction',
'Books & Arts',
'Career Column',
'Career Feature',
'Comment',
'Correspondence',
'Editorial',
'Futures',
'Letter',
'Nature Briefing',
'Nature Index',
'Nature Podcast',
'News',
'News & Views',
'News Feature',
'Outlook',
'Research Highlight',
'Seven Days',
'World View')
